name: Feature to main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check-feature-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for console.log || Console.WriteLine
        run: |
          if grep -r -E "console\.log\(|Console\.WriteLine\(" .; then
            echo "Log Statements found! Failing Test."
            exit 1
          else
            echo "No log statements found! Test Passed."
          fi

      - name: Check for merge conflicts
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff --no-commit $GITHUB_HEAD_REF || true
          if git diff --check --diff-filter=U | grep -q '^'; then
            echo "Merge conflict detected! Failing Job."
            exit 1
          else
            echo "No Merge Conflicts Found"
          fi

  check-merge-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged by jefta-jose
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            MERGER_USERNAME="${{ github.event.pull_request.merged_by.login }}"
            if [[ "$MERGER_USERNAME" == "jefta-jose" ]]; then
              echo "PR merged by jefta-jose. Proceeding."
            else
              echo "PR was merged by $MERGER_USERNAME, not jefta-jose. Rejecting."
              exit 1
            fi
          else
            echo "PR was not merged. Skipping."
            exit 0
          fi
