name: Staging to Main

on:
  push:
    branches:
      - staging

jobs:
  check-merge-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged by jefta-jose
        run: |
          # Check if the pull request was merged
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            # Get the GitHub username of the user who merged the PR
            MERGER_USERNAME="${{ github.event.pull_request.merged_by.login }}"

            # Check if the merger is jefta-jose
            if [[ "$MERGER_USERNAME" == "jefta-jose" ]]; then
              echo "PR merged by jefta-jose. All good!"
            else
              echo "PR was merged by $MERGER_USERNAME, not jefta-jose. Rejecting."
              exit 1
            fi
          else
            echo "PR was not merged. Skipping."
            exit 0
          fi

  merge-staging-to-main:
    needs: check-merge-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch latest changes
        run: |
          git fetch --all

      - name: Merge staging into main
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge origin/staging --no-ff --allow-unrelated-histories -m "Merge staging to main" || {
            echo "Merge conflict detected! Manual resolution required."
            exit 1
          }
          git push origin main
