name: "Check Branch"
on:
  pull_request:
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "staging" ]]; then
            echo "Error: You can only create a PR to main from the staging branch."
            exit 1
          fi